import {
    IconAdjustmentsHorizontal,
    IconArrowLeft,
    IconArrowRight,
    IconBabyCarriage,
    IconBell,
    IconBellFilled,
    IconBrandBadoo,
    IconCat,
    IconCheck,
    IconChefHat,
    IconChevronDown,
    IconChevronUp,
    IconCookieOff,
    IconCross,
    IconGlassFull,
    IconHeartHandshake,
    IconInfoCircle,
    IconLogout,
    IconMapPin,
    IconMessagePlus,
    IconNews,
    IconPlus,
    IconPray,
    IconReload,
    IconRuler2,
    IconSearch,
    IconSettings,
    IconSmoking,
    IconSparkles,
    IconTriangleInvertedFilled,
    IconUser,
    IconVocabulary,
    IconWoman,
    IconX,
} from "@tabler/icons-react";

import { default as arrowTarget } from "../customIcons/arrowTarget.png";
import { default as cardHeart } from "../customIcons/cardHeart.png";
import { default as googleLogo } from "../customIcons/googleLogo.png";
import { default as graphBar } from "../customIcons/graphBar.png";
import { default as heartCircle } from "../customIcons/heartCircle.svg";
import { default as instagram } from "../customIcons/instagram.png";

export const ICONS = {
    "arrow-left": IconArrowLeft,
    "arrow-right": IconArrowRight,
    "adjustments-horizontal": IconAdjustmentsHorizontal,
    bell: IconBell,
    "bell-filled": IconBellFilled,
    check: IconCheck,
    "chevron-down": IconChevronDown,
    "chevron-down-fill": IconTriangleInvertedFilled,
    "chevron-up": IconChevronUp,
    heart: IconHeartHandshake,
    "heart-smily": IconBrandBadoo,
    info: IconInfoCircle,
    location: IconMapPin,
    plus: IconPlus,
    search: IconSearch,
    setting: IconSettings,
    twinkle: IconSparkles,
    user: IconUser,
    x: IconX,
    google: googleLogo,
    "card-heart": cardHeart,
    "graph-bar": graphBar,
    "arrow-target": arrowTarget,
    instagram: instagram,
    "map-pin": IconMapPin,
    cat: IconCat,
    "chef-hat": IconChefHat,
    cross: IconCross,
    news: IconNews,
    pray: IconPray,
    "heart-circle": heartCircle,
    woman: IconWoman,
    ruler2: IconRuler2,
    vocabulary: IconVocabulary,
    glassFull: IconGlassFull,
    smoking: IconSmoking,
    babyCarriage: IconBabyCarriage,
    cookieOff: IconCookieOff,
    reload: IconReload,
    messagePlus: IconMessagePlus,
    logout: IconLogout,
} as const;
